samples:
  1: 
    - fastq/GM1-1.fastq
    - fastq/GM1-2.fastq
reads:
  - 1
  - 2
workdir: /fast/users/szyskam_c/work/tutorial/whRNASeq
setup:
  run: PE
  phred: 64
  readlength: 75
  fastq_comp: ''
alignment:
  tool: STAR
  threads: 16
  annotation: GENCODE28
  refgen: HG38
trim:
  use_trim: True
  threads: 64
  mode: AVGQUAL:20 SLIDINGWINDOW:5:25
  file_name:
    - trim
    - trim_UP