samples:
  1: 
    - fastq/GM1-1.fastq
    - fastq/GM1-2.fastq
reads:
  - 1
  - 2
ref:
  fa: $HG38
  gtf: $HG38GC28
  refgen: /fast/users/szyskam_c/static/ref/annotation/
workdir: $HOME/work/tuto/wHRNASeq
setup:
  run: PE
  phred: 64
alignment:
  threads: 64
trim:
  threads: 64
  mode: AVGQUAL:20 TRAILING:20 SLIDINGWINDOW:5:25
  file_name:
    - "trim"
    - "trim_UP"
