samples:
  1: 
    - fastq/GM1-1.fastq
    - fastq/GM1-2.fastq
reads:
  - 1
  - 2
ref: 
  refgen: /fast/users/szyskam_c/static/ref/annotation/hg38gc28
workdir: fullWRKDIR
setup:
  run: PE
  phred: 64
  readlength: 75
alignment:
  tool: "STAR"
  threads: 16
  annotation: "GENCODE28"
  refgen: HG38
trim:
  threads: 64
  mode: AVGQUAL:20 SLIDINGWINDOW:5:25
  file_name:
    - "trim"
    - "trim_UP"